name: ensam_assisstant
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.5.0+15

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter_colorpicker: ^0.6.0
  intl:
  settings_ui: ^2.0.1
  dio: ^4.0.0
  fl_chart: ^0.46.0
  flutter_platform_widgets: ^1.9.5
  ars_progress_dialog: ^0.0.1
  flutter_zoom_drawer: ^2.1.0
  progress_dialog: ^1.2.4
  splashscreen:
  animated_dialog_box: ^0.0.2
  html: ^0.15.0
  dio_cookie_manager: ^2.0.0
  url_launcher: ^6.0.3
  provider: ^6.0.2
  path_provider: ^2.0.3
  csv: 5.0.1
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  workmanager: ^0.4.1
  flutter_local_notifications: ^9.9.1
  http: ^0.13.3
  flutter_native_timezone: ^2.0.0
  rxdart: ^0.27.2
  shared_preferences: ^2.0.13

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - Assets/
    - Assets/app_icon_beta.png
    - Assets/image2.png
    - Assets/ENSAM-meknes-compus.jpg
    - Assets/tese.pdf
    - Assets/modsList.json
    - Assets/icons8-brief-90.png
    - Assets/icons8-attendance-100.png
    - Assets/icons8-grades-100.png
    - Assets/s1_icon.ico
    - Assets/s2_icon.ico
    - Assets/calendar.json

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: SFUIDisplay
      fonts:
        - asset: Assets/sf-ui-display-light.otf
    - family: Roboto
      fonts:
        - asset: Assets/Fonts/Nunito-VariableFont_wght.ttf
        - asset: Assets/Fonts/Nunito-Italic.ttf
          style: italic
        - asset: Assets/Fonts/Nunito-Bold.ttf
          weight: 900

  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages

